# Mode
production: false

# Minimal log level
log_level: trace

# Backend url
backend_scheme: http         # Scheme
backend_base_url: localhost  # Base service url
backend_port: 5000           # Backend port

# API urls
backend_contracts_method: contracts
backend_logs_method: log